/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import clases.CallCenter;
import clases.Empleado;
import java.util.ArrayList;
import java.util.LinkedList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultTreeCellEditor;
import model.ModelEmpleado;

/**
 *
 * @author derhe
 */
public class frmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmPrincipal
     */
    Empleado empleado;
    CallCenter liquidacion = new CallCenter();
    ModelEmpleado modelEmpleado = new ModelEmpleado();
    LinkedList<Empleado> empleadoLista = new LinkedList<>();
    public frmPrincipal() {
        initComponents();
        this.empleadoLista = modelEmpleado.listaEmpleados();
        this.listaEmpleado();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPaneGrupo = new javax.swing.JTabbedPane();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListEmpleado = new javax.swing.JList<>();
        jPanelNomina = new javax.swing.JPanel();
        jPanelInfoEmpleado = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelCodigo = new javax.swing.JLabel();
        jTextFieldCodigo = new javax.swing.JTextField();
        jButtonConsultar = new javax.swing.JButton();
        jLabelCedula = new javax.swing.JLabel();
        jTextFieldCedula = new javax.swing.JTextField();
        jButtonLimpiarCampos = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabelInfoNomina = new javax.swing.JLabel();
        jLabelSalario = new javax.swing.JLabel();
        jLabelHorasExtras = new javax.swing.JLabel();
        jCheckBoxAuxilioTransporte = new javax.swing.JCheckBox();
        jTextFieldSalario = new javax.swing.JTextField();
        jTextFieldHoraExtra = new javax.swing.JTextField();
        jLabelNombre = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabelApellido = new javax.swing.JLabel();
        jTextFieldApellido = new javax.swing.JTextField();
        jButtonGenerarNomina = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabelTotalNominaEmpleado = new javax.swing.JLabel();
        jTextFieldTotalNomina = new javax.swing.JTextField();
        jTextFieldTotalPrestaciones = new javax.swing.JTextField();
        jLabelTotalPrestaciones = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabelInfoNomina1 = new javax.swing.JLabel();
        jLabelSalario1 = new javax.swing.JLabel();
        jLabelHorasExtras1 = new javax.swing.JLabel();
        jCheckBoxAuxilioTransporteCrear = new javax.swing.JCheckBox();
        jTextFieldSalarioCrear = new javax.swing.JTextField();
        jTextFieldHoraExtraCrear = new javax.swing.JTextField();
        jLabelNombre1 = new javax.swing.JLabel();
        jTextFieldNombreCrear = new javax.swing.JTextField();
        jLabelApellido1 = new javax.swing.JLabel();
        jTextFieldApellidoCrear = new javax.swing.JTextField();
        jButtonGenerarNomina1 = new javax.swing.JButton();
        jTextFieldCedulaCrear = new javax.swing.JTextField();
        jLabelCedulaCrear = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabelInfoNomina2 = new javax.swing.JLabel();
        jLabelSalario2 = new javax.swing.JLabel();
        jLabelHorasExtras2 = new javax.swing.JLabel();
        jCheckBoxAuxilioTransporteEditar = new javax.swing.JCheckBox();
        jTextFieldSalarioEditar = new javax.swing.JTextField();
        jTextFieldHoraExtraEditar = new javax.swing.JTextField();
        jLabelNombre2 = new javax.swing.JLabel();
        jTextFieldNombreEditar = new javax.swing.JTextField();
        jLabelApellido2 = new javax.swing.JLabel();
        jTextFieldApellidoEditar = new javax.swing.JTextField();
        jButtonGuardarCambios = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanelInfoEmpleado1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabelCodigo1 = new javax.swing.JLabel();
        jTextFieldCodigoEditar = new javax.swing.JTextField();
        jButtonConsultarEditar = new javax.swing.JButton();
        jLabelCedulaEditar = new javax.swing.JLabel();
        jTextFieldCedulaEditar = new javax.swing.JTextField();
        jButtonLimpiarCamposEditar = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanelInfoEmpleado2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabelCodigo2 = new javax.swing.JLabel();
        jTextFieldCodigoEliminar = new javax.swing.JTextField();
        jButtonConsultarEliminar = new javax.swing.JButton();
        jPanel16 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButtonProcesar = new javax.swing.JButton();
        jScrollPaneLiquidacion = new javax.swing.JScrollPane();
        jListLiquidacion = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Lista de Empleados");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(221, 221, 221)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(222, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jListEmpleado.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Empleado 1", "Empleado 2", "Empleado 3", "Empleado 4", "Empleado 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jListEmpleado);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPaneGrupo.addTab("Empleados", jPanel9);

        jPanelInfoEmpleado.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Consultar Empleado");

        jLabelCodigo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelCodigo.setText("Codigo:");

        jTextFieldCodigo.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jButtonConsultar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonConsultar.setText("consultar");
        jButtonConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultarActionPerformed(evt);
            }
        });

        jLabelCedula.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelCedula.setText("Cedula:");

        jTextFieldCedula.setBackground(new java.awt.Color(255, 255, 255));

        jButtonLimpiarCampos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonLimpiarCampos.setText("Limpiar campos");
        jButtonLimpiarCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarCamposActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelInfoEmpleadoLayout = new javax.swing.GroupLayout(jPanelInfoEmpleado);
        jPanelInfoEmpleado.setLayout(jPanelInfoEmpleadoLayout);
        jPanelInfoEmpleadoLayout.setHorizontalGroup(
            jPanelInfoEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInfoEmpleadoLayout.createSequentialGroup()
                .addGroup(jPanelInfoEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelInfoEmpleadoLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addGroup(jPanelInfoEmpleadoLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabelCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                        .addComponent(jLabelCedula)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanelInfoEmpleadoLayout.createSequentialGroup()
                .addGap(207, 207, 207)
                .addComponent(jButtonConsultar)
                .addGap(18, 18, 18)
                .addComponent(jButtonLimpiarCampos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelInfoEmpleadoLayout.setVerticalGroup(
            jPanelInfoEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInfoEmpleadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelInfoEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCodigo)
                    .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCedula)
                    .addComponent(jTextFieldCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelInfoEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonConsultar)
                    .addComponent(jButtonLimpiarCampos))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jPanel5.setForeground(new java.awt.Color(204, 204, 204));

        jLabelInfoNomina.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelInfoNomina.setForeground(new java.awt.Color(153, 153, 153));
        jLabelInfoNomina.setText("Informacion Nomina Empleado");

        jLabelSalario.setText("Salario:");

        jLabelHorasExtras.setText("Valor Horas Extras:");

        jCheckBoxAuxilioTransporte.setText("Auxilio Transporte");

        jTextFieldSalario.setEditable(false);
        jTextFieldSalario.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTextFieldHoraExtra.setEditable(false);
        jTextFieldHoraExtra.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jCheckBoxAuxilioTransporte)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabelHorasExtras)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldHoraExtra))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabelInfoNomina)
                        .addGap(0, 37, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabelSalario)
                        .addGap(66, 66, 66)
                        .addComponent(jTextFieldSalario)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelInfoNomina)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelSalario)
                    .addComponent(jTextFieldSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelHorasExtras)
                    .addComponent(jTextFieldHoraExtra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxAuxilioTransporte)
                .addContainerGap())
        );

        jLabelNombre.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelNombre.setText("Nombre:");

        jTextFieldNombre.setEditable(false);

        jLabelApellido.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelApellido.setText("Apellido:");

        jTextFieldApellido.setEditable(false);

        jButtonGenerarNomina.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonGenerarNomina.setText("Generar Nomina");
        jButtonGenerarNomina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGenerarNominaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonGenerarNomina))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextFieldNombre, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNombre, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelApellido, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldApellido, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabelNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelApellido)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jButtonGenerarNomina)
                .addContainerGap())
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelTotalNominaEmpleado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelTotalNominaEmpleado.setText("Total Nómina Empleado:");

        jTextFieldTotalNomina.setEditable(false);
        jTextFieldTotalNomina.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldTotalNomina.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldTotalNomina.setText("0");

        jTextFieldTotalPrestaciones.setEditable(false);
        jTextFieldTotalPrestaciones.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldTotalPrestaciones.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldTotalPrestaciones.setText("0");

        jLabelTotalPrestaciones.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelTotalPrestaciones.setText("Total Prestaciones:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelTotalNominaEmpleado)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldTotalNomina, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelTotalPrestaciones)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldTotalPrestaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTotalNominaEmpleado)
                    .addComponent(jTextFieldTotalNomina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTotalPrestaciones)
                    .addComponent(jTextFieldTotalPrestaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelNominaLayout = new javax.swing.GroupLayout(jPanelNomina);
        jPanelNomina.setLayout(jPanelNominaLayout);
        jPanelNominaLayout.setHorizontalGroup(
            jPanelNominaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNominaLayout.createSequentialGroup()
                .addGroup(jPanelNominaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelInfoEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelNominaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(45, 45, 45))
        );
        jPanelNominaLayout.setVerticalGroup(
            jPanelNominaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNominaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelInfoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPaneGrupo.addTab("Liq. Nomina", jPanelNomina);

        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jPanel7.setForeground(new java.awt.Color(204, 204, 204));

        jLabelInfoNomina1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelInfoNomina1.setForeground(new java.awt.Color(153, 153, 153));
        jLabelInfoNomina1.setText("Informacion Nomina Empleado");

        jLabelSalario1.setText("Salario:");

        jLabelHorasExtras1.setText("Valor Horas Extras:");

        jCheckBoxAuxilioTransporteCrear.setText("Auxilio Transporte");

        jTextFieldSalarioCrear.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldSalarioCrear.setText("0");

        jTextFieldHoraExtraCrear.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldHoraExtraCrear.setText("0");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabelInfoNomina1))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabelHorasExtras1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldHoraExtraCrear, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabelSalario1)
                                .addGap(66, 66, 66)
                                .addComponent(jTextFieldSalarioCrear)))))
                .addContainerGap())
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jCheckBoxAuxilioTransporteCrear)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelInfoNomina1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSalario1)
                    .addComponent(jTextFieldSalarioCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelHorasExtras1)
                    .addComponent(jTextFieldHoraExtraCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBoxAuxilioTransporteCrear)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabelNombre1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelNombre1.setText("Nombre:");

        jLabelApellido1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelApellido1.setText("Apellido:");

        jButtonGenerarNomina1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonGenerarNomina1.setText("Guardar");
        jButtonGenerarNomina1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGenerarNomina1ActionPerformed(evt);
            }
        });

        jLabelCedulaCrear.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelCedulaCrear.setText("Cedula:");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldNombreCrear)
                    .addComponent(jTextFieldApellidoCrear)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNombre1)
                            .addComponent(jLabelApellido1)
                            .addComponent(jLabelCedulaCrear))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jTextFieldCedulaCrear))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonGenerarNomina1)
                .addGap(279, 279, 279))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelNombre1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jTextFieldNombreCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelApellido1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldApellidoCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelCedulaCrear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldCedulaCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jButtonGenerarNomina1)
                .addContainerGap())
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Registrar Empleado");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(252, 252, 252)
                .addComponent(jLabel2)
                .addContainerGap(232, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(207, Short.MAX_VALUE))
        );

        jTabbedPaneGrupo.addTab("Crear empleado", jPanel2);

        jPanel11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jPanel12.setForeground(new java.awt.Color(204, 204, 204));

        jLabelInfoNomina2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelInfoNomina2.setForeground(new java.awt.Color(153, 153, 153));
        jLabelInfoNomina2.setText("Informacion Nomina Empleado");

        jLabelSalario2.setText("Salario:");

        jLabelHorasExtras2.setText("Valor Horas Extras:");

        jCheckBoxAuxilioTransporteEditar.setText("Auxilio Transporte");

        jTextFieldSalarioEditar.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldSalarioEditar.setText("0");

        jTextFieldHoraExtraEditar.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldHoraExtraEditar.setText("0");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabelInfoNomina2))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel12Layout.createSequentialGroup()
                                .addComponent(jLabelHorasExtras2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldHoraExtraEditar, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
                            .addGroup(jPanel12Layout.createSequentialGroup()
                                .addComponent(jLabelSalario2)
                                .addGap(66, 66, 66)
                                .addComponent(jTextFieldSalarioEditar)))))
                .addContainerGap())
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jCheckBoxAuxilioTransporteEditar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelInfoNomina2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSalario2)
                    .addComponent(jTextFieldSalarioEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelHorasExtras2)
                    .addComponent(jTextFieldHoraExtraEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBoxAuxilioTransporteEditar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabelNombre2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelNombre2.setText("Nombre:");

        jLabelApellido2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelApellido2.setText("Apellido:");

        jButtonGuardarCambios.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonGuardarCambios.setText("Guardar Cambios");
        jButtonGuardarCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarCambiosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldNombreEditar)
                    .addComponent(jTextFieldApellidoEditar)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNombre2)
                            .addComponent(jLabelApellido2))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonGuardarCambios)
                .addGap(242, 242, 242))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelNombre2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNombreEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelApellido2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldApellidoEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonGuardarCambios)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel13.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Editar Empleados");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelInfoEmpleado1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Consultar Empleado");

        jLabelCodigo1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelCodigo1.setText("Codigo:");

        jTextFieldCodigoEditar.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jButtonConsultarEditar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonConsultarEditar.setText("consultar");
        jButtonConsultarEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultarEditarActionPerformed(evt);
            }
        });

        jLabelCedulaEditar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelCedulaEditar.setText("Cedula:");

        jButtonLimpiarCamposEditar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonLimpiarCamposEditar.setText("Limpiar campos");
        jButtonLimpiarCamposEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarCamposEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelInfoEmpleado1Layout = new javax.swing.GroupLayout(jPanelInfoEmpleado1);
        jPanelInfoEmpleado1.setLayout(jPanelInfoEmpleado1Layout);
        jPanelInfoEmpleado1Layout.setHorizontalGroup(
            jPanelInfoEmpleado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInfoEmpleado1Layout.createSequentialGroup()
                .addGroup(jPanelInfoEmpleado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelInfoEmpleado1Layout.createSequentialGroup()
                        .addGap(238, 238, 238)
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInfoEmpleado1Layout.createSequentialGroup()
                        .addGroup(jPanelInfoEmpleado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelInfoEmpleado1Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jLabelCodigo1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldCodigoEditar)
                                .addGap(18, 18, 18))
                            .addGroup(jPanelInfoEmpleado1Layout.createSequentialGroup()
                                .addGap(171, 171, 171)
                                .addComponent(jButtonConsultarEditar)
                                .addGap(20, 20, 20)))
                        .addGroup(jPanelInfoEmpleado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelInfoEmpleado1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jButtonLimpiarCamposEditar))
                            .addGroup(jPanelInfoEmpleado1Layout.createSequentialGroup()
                                .addComponent(jLabelCedulaEditar)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldCedulaEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanelInfoEmpleado1Layout.setVerticalGroup(
            jPanelInfoEmpleado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInfoEmpleado1Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelInfoEmpleado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelInfoEmpleado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelCedulaEditar)
                        .addComponent(jTextFieldCedulaEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelInfoEmpleado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelCodigo1)
                        .addComponent(jTextFieldCodigoEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addGroup(jPanelInfoEmpleado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonConsultarEditar)
                    .addComponent(jButtonLimpiarCamposEditar))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelInfoEmpleado1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelInfoEmpleado1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(133, Short.MAX_VALUE))
        );

        jTabbedPaneGrupo.addTab("Editar Empelado", jPanel3);

        jPanel15.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Eliminar Empleados");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(254, 254, 254)
                .addComponent(jLabel7)
                .addContainerGap(231, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelInfoEmpleado2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Consultar Empleado");

        jLabelCodigo2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelCodigo2.setText("Codigo:");

        jTextFieldCodigoEliminar.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jButtonConsultarEliminar.setText("consultar");
        jButtonConsultarEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultarEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelInfoEmpleado2Layout = new javax.swing.GroupLayout(jPanelInfoEmpleado2);
        jPanelInfoEmpleado2.setLayout(jPanelInfoEmpleado2Layout);
        jPanelInfoEmpleado2Layout.setHorizontalGroup(
            jPanelInfoEmpleado2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInfoEmpleado2Layout.createSequentialGroup()
                .addGap(234, 234, 234)
                .addGroup(jPanelInfoEmpleado2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelInfoEmpleado2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel8))
                    .addGroup(jPanelInfoEmpleado2Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jButtonConsultarEliminar))
                    .addGroup(jPanelInfoEmpleado2Layout.createSequentialGroup()
                        .addComponent(jLabelCodigo2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldCodigoEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(224, Short.MAX_VALUE))
        );
        jPanelInfoEmpleado2Layout.setVerticalGroup(
            jPanelInfoEmpleado2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInfoEmpleado2Layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelInfoEmpleado2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCodigo2)
                    .addComponent(jTextFieldCodigoEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jButtonConsultarEliminar)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelInfoEmpleado2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelInfoEmpleado2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(329, Short.MAX_VALUE))
        );

        jTabbedPaneGrupo.addTab("Eliminar Empleado", jPanel14);

        jPanel17.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Año: ");

        jTextField1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField1.setText("2022");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("Mes:");

        jComboBox1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));

        jButtonProcesar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonProcesar.setText("Procesar");
        jButtonProcesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProcesarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(89, 89, 89)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addGap(266, 266, 266)
                        .addComponent(jButtonProcesar)))
                .addContainerGap(153, Short.MAX_VALUE))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonProcesar)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jScrollPaneLiquidacion.setViewportView(jListLiquidacion);

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPaneLiquidacion)))
                .addContainerGap())
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneLiquidacion, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPaneGrupo.addTab("Liq. Nomina General", jPanel16);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPaneGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 694, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPaneGrupo)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonConsultarEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarEditarActionPerformed
        // TODO add your handling code here:
         if (jTextFieldCodigoEditar.getText().equals("")) {
           empleado = modelEmpleado.validarCedula(jTextFieldCedulaEditar.getText());
        }else
            if (jTextFieldCedulaEditar.getText().equals("")) {
            empleado = modelEmpleado.consultaEmpleadoId(jTextFieldCodigoEditar.getText());
        }
        if (empleado == null) {
            JOptionPane.showMessageDialog(rootPane, "empleado no registrado");
            jTextFieldNombreEditar.setText("");
            jTextFieldApellidoEditar.setText("");
            jTextFieldSalarioEditar.setText("");
            jTextFieldHoraExtraEditar.setText("");
            jCheckBoxAuxilioTransporteEditar.setSelected(false);
        }else{
            jTextFieldCodigoEditar.setText(empleado.getId());
            jTextFieldNombreEditar.setText(empleado.getNombre());
            jTextFieldApellidoEditar.setText(empleado.getApellido());
            jTextFieldSalarioEditar.setText(String.valueOf(empleado.getSalario()));
            jTextFieldHoraExtraEditar.setText(String.valueOf(empleado.getHorasExtra()));
            jTextFieldCedulaEditar.setText(empleado.getCedula());
            jCheckBoxAuxilioTransporteEditar.setSelected(empleado.isAuxilioTransporte());
            jTextFieldCodigoEditar.setEditable(false);
        }
    }//GEN-LAST:event_jButtonConsultarEditarActionPerformed

    private void jButtonGuardarCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarCambiosActionPerformed
        // TODO add your handling code here:
        try {
            if (jTextFieldNombreEditar.getText().equals("") || 
                jTextFieldApellidoEditar.getText().equals("") ||
                 jTextFieldCedulaEditar.getText().equals("") ||
                Double.valueOf(jTextFieldSalarioEditar.getText())<= 0 ||
                Float.valueOf(jTextFieldHoraExtraEditar.getText())< 0
                ) {
                JOptionPane.showMessageDialog(rootPane,"Debe completar todos los campos y el salario debe ser mayor que cero");
            }else{
                if(modelEmpleado.editarEmpleado(Integer.valueOf(jTextFieldCodigoEditar.getText()),
                    jTextFieldNombreEditar.getText(), jTextFieldApellidoEditar.getText(),
                    Float.valueOf(jTextFieldHoraExtraEditar.getText()),
                    jCheckBoxAuxilioTransporteEditar.isSelected(),
                    Double.valueOf(jTextFieldSalarioEditar.getText()),
                    jTextFieldCedulaEditar.getText())){

                JOptionPane.showMessageDialog(rootPane,"Usuario modificado");
                jTextFieldNombreEditar.setText("");
                jTextFieldCodigoEditar.setText("");
                jTextFieldApellidoEditar.setText("");
                jTextFieldSalarioEditar.setText("0");
                jTextFieldHoraExtraEditar.setText("0");
                jTextFieldCedulaEditar.setText("");
                jCheckBoxAuxilioTransporteEditar.setSelected(false);
                jTextFieldCodigoEditar.setEditable(true);
                this.empleadoLista = modelEmpleado.listaEmpleados();
                this.listaEmpleado();
            }else{
                JOptionPane.showMessageDialog(rootPane,"verifique los datos Usuario NO actualizado");
            }

        }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane,"Error: Usuario no Se Actualizo");
        }
    }//GEN-LAST:event_jButtonGuardarCambiosActionPerformed

    private void jButtonGenerarNomina1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGenerarNomina1ActionPerformed
        // TODO add your handling code here:
        try {
            if (jTextFieldNombreCrear.getText().equals("") ||
                    jTextFieldApellidoCrear.getText().equals("") || 
                    Double.valueOf(jTextFieldSalarioCrear.getText())<= 0 || 
                    Float.valueOf(jTextFieldHoraExtraCrear.getText())< 0 ||
                    jTextFieldCedulaCrear.getText().equals("")) {
                JOptionPane.showMessageDialog(rootPane,"Debe completar todos los campos y el salario debe ser mayor que cero");
            }else{
                empleado = modelEmpleado.validarCedula(jTextFieldCedulaCrear.getText());
                if (empleado != null) {
                    JOptionPane.showMessageDialog(rootPane,"el empleado con identificacion " + jTextFieldCedulaCrear.getText()
                                                            +" ya existe\n su nombre es nombre: " 
                                                            + empleado.getNombre() );
                } else {
                     if(modelEmpleado.insertarEmpleado(
                        jTextFieldNombreCrear.getText(),jTextFieldApellidoCrear.getText(),
                        Float.valueOf(jTextFieldHoraExtraCrear.getText()),
                        jCheckBoxAuxilioTransporteCrear.isSelected(),
                        Double.valueOf(jTextFieldSalarioCrear.getText()),
                        jTextFieldCedulaCrear.getText())){
                JOptionPane.showMessageDialog(rootPane,"Usuario guardado");
                
                jTextFieldNombreCrear.setText("");
                jTextFieldApellidoCrear.setText("");
                jTextFieldCedulaCrear.setText("");
                jTextFieldSalarioCrear.setText("0");
                jTextFieldHoraExtraCrear.setText("0");
                jCheckBoxAuxilioTransporteCrear.setSelected(false);
                this.empleadoLista = modelEmpleado.listaEmpleados();
                this.listaEmpleado();
            }else{
                JOptionPane.showMessageDialog(rootPane,"Error: Usuario no guardado");
            }
                    
                }              
        }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane,"Error: Usuario no guardado");
        }
    }//GEN-LAST:event_jButtonGenerarNomina1ActionPerformed

    private void jButtonGenerarNominaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGenerarNominaActionPerformed
        // TODO add your handling code here:

        double nomina;
        double prestacion;
        Empleado empleado = modelEmpleado.consultaEmpleadoId(jTextFieldCodigo.getText());
        nomina = liquidacion.liquidarNominaEmp(empleado);
        prestacion = liquidacion.liquidarPrestacionesempd(empleado);
        jTextFieldTotalNomina.setText(String.valueOf(Math.round(nomina)));
        jTextFieldTotalPrestaciones.setText(String.valueOf(Math.round(prestacion)));
    }//GEN-LAST:event_jButtonGenerarNominaActionPerformed

    private void jButtonConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarActionPerformed
        // TODO add your handling code here:
        

       if (jTextFieldCodigo.getText().equals("")) {
           empleado = modelEmpleado.validarCedula(jTextFieldCedula.getText());
        }else
            if (jTextFieldCedula.getText().equals("")) {
            empleado = modelEmpleado.consultaEmpleadoId(jTextFieldCodigo.getText());
        }
        
        if (empleado == null) {
            JOptionPane.showMessageDialog(rootPane, "empleado no registrado");
            jTextFieldNombre.setText("");
            jTextFieldApellido.setText("");
            jTextFieldSalario.setText("");
            jTextFieldHoraExtra.setText("");
            jTextFieldCedula.setText("");
            jCheckBoxAuxilioTransporte.setSelected(false);
            jTextFieldTotalNomina.setText("0");
            jTextFieldTotalPrestaciones.setText("0");
            jTextFieldCodigo.setText("");
        }else{
            jTextFieldCodigo.setText(empleado.getId());
            jTextFieldNombre.setText(empleado.getNombre());
            jTextFieldApellido.setText(empleado.getApellido());
            jTextFieldSalario.setText(String.valueOf(empleado.getSalario()));
            jTextFieldHoraExtra.setText(String.valueOf(empleado.getHorasExtra()));
            jTextFieldCedula.setText(empleado.getCedula());
            jCheckBoxAuxilioTransporte.setSelected(empleado.isAuxilioTransporte());
            jTextFieldTotalNomina.setText("0");
            jTextFieldTotalPrestaciones.setText("0");
            jTextFieldCodigo.setEditable(false);
            jTextFieldCedula.setEditable(false);
        }
    }//GEN-LAST:event_jButtonConsultarActionPerformed

    private void jButtonConsultarEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarEliminarActionPerformed
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(rootPane, "Esta seguro de eliminar este empleado?");
        if(confirm == JOptionPane.YES_OPTION){
            if (modelEmpleado.EliminarEmpleado(jTextFieldCodigoEliminar.getText())) {
                   JOptionPane.showMessageDialog(rootPane, "empleado eliminado");
                   this.empleadoLista = modelEmpleado.listaEmpleados();
                    this.listaEmpleado();
            }else{
                 JOptionPane.showMessageDialog(rootPane, "No se pudo eliminar el usuario");
            }
        }else{
            if(confirm == JOptionPane.NO_OPTION){
              JOptionPane.showMessageDialog(rootPane, "empleado NO eliminado");
            }   
        }
    }//GEN-LAST:event_jButtonConsultarEliminarActionPerformed

    private void jButtonProcesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProcesarActionPerformed
        DefaultListModel  model = new DefaultListModel();
        ArrayList<Empleado> listEmpleado = new ArrayList<>();
        
        int index = 0;
        for (Empleado empleado : empleadoLista) {
            double valorLiquidarEmpleado = liquidacion.liquidarNominaEmp(empleado);
            double valorPrestacionEmpleado = liquidacion.liquidarPrestacionesempd(empleado);
            String data = (index+1)+") - Id: "+empleado.getId() +" - Nombre: "+ 
                            empleado.getNombre()+"- Apellido: "+ empleado.getApellido()+
                            " - Cedula: \n"+ empleado.getCedula()+ " - liquidacion: " + Math.round(valorLiquidarEmpleado)+
                            " - Prestaciones: "+ Math.round(valorPrestacionEmpleado);
            model.add(index, data);
            listEmpleado.add(empleado);
            index++;
            
        }
        jListLiquidacion.setModel(model);
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jButtonProcesarActionPerformed

    private void jButtonLimpiarCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarCamposActionPerformed
        // TODO add your handling code here:
        jTextFieldCodigo.setText("");
        jTextFieldCedula.setText("");
        jTextFieldNombre.setText("");
        jTextFieldApellido.setText("");
        jTextFieldSalario.setText("");
        jTextFieldHoraExtra.setText("");
        jTextFieldCodigo.setEditable(true);
        jTextFieldCedula.setEditable(true);
    }//GEN-LAST:event_jButtonLimpiarCamposActionPerformed

    private void jButtonLimpiarCamposEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarCamposEditarActionPerformed
        // TODO add your handling code here:
        jTextFieldCodigoEditar.setText("");
        jTextFieldCedulaEditar.setText("");
        jTextFieldNombreEditar.setText("");
        jTextFieldApellidoEditar.setText("");
        jTextFieldSalarioEditar.setText("");
        jTextFieldHoraExtraEditar.setText("");
        jTextFieldCodigoEditar.setEditable(true);
        jTextFieldCedulaEditar.setEditable(true);
        
    }//GEN-LAST:event_jButtonLimpiarCamposEditarActionPerformed
    
    // listado de empelados
    private void listaEmpleado(){
         DefaultListModel  model = new DefaultListModel();
        int index = 0;
        for (Empleado empleado : empleadoLista) {
            String data = (index+1)+") Id: "+empleado.getId() +"- Nombre: "+ empleado.getNombre()+" "+ empleado.getApellido();
            model.add(index, data);
            index++;
            
        }
        jListEmpleado.setModel(model);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConsultar;
    private javax.swing.JButton jButtonConsultarEditar;
    private javax.swing.JButton jButtonConsultarEliminar;
    private javax.swing.JButton jButtonGenerarNomina;
    private javax.swing.JButton jButtonGenerarNomina1;
    private javax.swing.JButton jButtonGuardarCambios;
    private javax.swing.JButton jButtonLimpiarCampos;
    private javax.swing.JButton jButtonLimpiarCamposEditar;
    private javax.swing.JButton jButtonProcesar;
    private javax.swing.JCheckBox jCheckBoxAuxilioTransporte;
    private javax.swing.JCheckBox jCheckBoxAuxilioTransporteCrear;
    private javax.swing.JCheckBox jCheckBoxAuxilioTransporteEditar;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelApellido;
    private javax.swing.JLabel jLabelApellido1;
    private javax.swing.JLabel jLabelApellido2;
    private javax.swing.JLabel jLabelCedula;
    private javax.swing.JLabel jLabelCedulaCrear;
    private javax.swing.JLabel jLabelCedulaEditar;
    private javax.swing.JLabel jLabelCodigo;
    private javax.swing.JLabel jLabelCodigo1;
    private javax.swing.JLabel jLabelCodigo2;
    private javax.swing.JLabel jLabelHorasExtras;
    private javax.swing.JLabel jLabelHorasExtras1;
    private javax.swing.JLabel jLabelHorasExtras2;
    private javax.swing.JLabel jLabelInfoNomina;
    private javax.swing.JLabel jLabelInfoNomina1;
    private javax.swing.JLabel jLabelInfoNomina2;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelNombre1;
    private javax.swing.JLabel jLabelNombre2;
    private javax.swing.JLabel jLabelSalario;
    private javax.swing.JLabel jLabelSalario1;
    private javax.swing.JLabel jLabelSalario2;
    private javax.swing.JLabel jLabelTotalNominaEmpleado;
    private javax.swing.JLabel jLabelTotalPrestaciones;
    private javax.swing.JList<String> jListEmpleado;
    private javax.swing.JList<String> jListLiquidacion;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanelInfoEmpleado;
    private javax.swing.JPanel jPanelInfoEmpleado1;
    private javax.swing.JPanel jPanelInfoEmpleado2;
    private javax.swing.JPanel jPanelNomina;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPaneLiquidacion;
    private javax.swing.JTabbedPane jTabbedPaneGrupo;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextFieldApellido;
    private javax.swing.JTextField jTextFieldApellidoCrear;
    private javax.swing.JTextField jTextFieldApellidoEditar;
    private javax.swing.JTextField jTextFieldCedula;
    private javax.swing.JTextField jTextFieldCedulaCrear;
    private javax.swing.JTextField jTextFieldCedulaEditar;
    private javax.swing.JTextField jTextFieldCodigo;
    private javax.swing.JTextField jTextFieldCodigoEditar;
    private javax.swing.JTextField jTextFieldCodigoEliminar;
    private javax.swing.JTextField jTextFieldHoraExtra;
    private javax.swing.JTextField jTextFieldHoraExtraCrear;
    private javax.swing.JTextField jTextFieldHoraExtraEditar;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldNombreCrear;
    private javax.swing.JTextField jTextFieldNombreEditar;
    private javax.swing.JTextField jTextFieldSalario;
    private javax.swing.JTextField jTextFieldSalarioCrear;
    private javax.swing.JTextField jTextFieldSalarioEditar;
    private javax.swing.JTextField jTextFieldTotalNomina;
    private javax.swing.JTextField jTextFieldTotalPrestaciones;
    // End of variables declaration//GEN-END:variables
}
